  name: Build Check

  on:
    pull_request:
      branches:
        - develop
      paths-ignore:
        - 'docs/**'
        - 'scripts/**'
        - 'README.md'
        - '.gitignore'

  jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up Java
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'adopt'

          - name: Build project
            run: |
              mvn clean install

          - name: Run unit tests
            run: |
              mvn test
